### ISSUE TITLE
关于Tradingview的一些重要概念的解释

### ISSUE THREAD

**Issue by SaberAlpha** [zlq4863947/proficient-tradingview#1]
关于这个课程我有几点建议和问题：
1、tradingview是什么，有何用途，相对与其他图表库来说有何优势等。这些问题解释清楚，一来有利于学习的人充分了解tradingview，二来也可以体现本课程的价值所在。
2、交易终端是什么，它和Charting Library有什么区别？
3、在讲解实例的过程中增加一些常用功能的设置的介绍。

**Comment by zlq4863947** [comment]
嗯 好的 有时间我整理一下
